### PR TITLE
Add Account resource

### PR DESCRIPTION
**Pull request by tizz98**
The Account resource is kinda funky. It's basically a singleton at this point so it could be accessed in one of 2 ways.

```python
a = Account.objects.get()
print(a.id, a.name)

# or
a = Account()
a.read()
print(a.id, a.name)
```

### CODE REVIEW

**Comment by bennullgraham** [comment]
Yeah OK, that looks sensible. While it feels a bit overkill having the whole `Account.objects` namespace to fetch one record, it's consistent and is better able to handle future ProsperWorks changes like multiple accounts (perhaps that's already a thing?)

**Comment by tizz98** [comment]
@bennullgraham yeah, I guess I went that route for consistency. It doesn't look like multiple accounts exist yet but I could definitely see it in the future.

**Comment by bennullgraham** [comment]
I've cherry-picked the Account commit from this MR, so effectively merged! Wanted to avoid the few unrelated commits getting merged too. Not a GitHub expert, is there a better way of handling that?

Cheers!

**Comment by bennullgraham** [comment]
Released in 0.7.0

**Pull request closed without merging**
