### PR TITLE
Add ability to fetch person by email

### PR DESCRIPTION
**Pull request by tizz98**
It would be awesome to be able to take advantage of this endpoint!

### CODE REVIEW

**Comment by bennullgraham** [comment]
What do you think about something like:

```python
class PersonManager(Manager):
    def get(self, id, email=None):
        if email is not None:
            # call fetch-by-email logic
        else:
            return super().get(id)
```

Then you get a nice API like:

```python
Person.objects.get(id=3)
Person.objects.get(email='foo@bar.org')
```

**Comment by tizz98** [comment]
@bennullgraham totally agree, updated to reflect that and added some tests.

**Comment by bennullgraham** [comment]
This is a great addition, thanks for the contribution :)

**Comment by bennullgraham** [comment]
Released in 0.7.0

**Pull request merged**
